[package]
edition = "2018"
name = "sub-batch"
version = "0.2.0"
authors = ["Kalle Lindström <kalind@posteo.se>"]
description = "Match and rename subtitle files to video files and perfom other batch operations on subtitle files."
homepage = "https://github.com/kl/sub-batch"
repository = "https://github.com/kl/sub-batch"
readme = "README.md"
keywords = ["subtitle", "subtitles"]
categories = ["command-line-utilities"]
exclude = ["/tests"]
license = "MIT"

[dependencies]
regex = "1.1.0"
subparse = "0.6.2"
clap = "2.32.0"
lazy_static = "1.2.0"
encoding_rs = "0.8.16"
anyhow = "1.0.26"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.1"
tempfile = "3.1.0"
glob = "0.3.0"